services:
  - type: web
    name: netsentinel
    env: python
    buildCommand: ""
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
    autoDeploy: true
